"""
SatQuery AI - Backend API Schemas

Defines the internal request/response contracts used by the backend.
"""

from typing import Any, Optional

from pydantic import BaseModel, Field

class TraceItem(BaseModel):
    step: int = 1
    stage: str = "Analysis Step"
    details: str = ""
    status: str = "completed"
    latency: str = "N/A"

class AnalysisRequest(BaseModel):
    """
    Internal analysis request.

    This model is created by the FastAPI layer after uploaded files
    have been saved to the backend filesystem.
    """

    query: str = Field(
        ...,
        min_length=1,
        description="Natural-language remote-sensing analysis query.",
    )

    image_paths: list[str] = Field(
        default_factory=list,
        description="Paths to uploaded images saved by the backend.",
    )

    mode: str = Field(
        default="auto_detect",
        description=(
            "Analysis mode: auto_detect, single_image, "
            "compare_images, or optical_sar."
        ),
    )

    metadata_a: dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata associated with image A.",
    )

    metadata_b: dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata associated with image B.",
    )


class DetectedTask(BaseModel):
    """
    Task selected by the query-understanding/routing stage.
    """

    task_id: str = Field(
        ...,
        description=(
            "Internal task identifier such as "
            "vqa, visual_grounding, change_detection, optical_sar."
        ),
    )

    title: str = Field(
        default="",
        description="Human-readable task name.",
    )

    reason: str = Field(
        default="",
        description="Why this task was selected.",
    )

    required_images: int = Field(
        default=1,
        ge=1,
        description="Number of images required by the task.",
    )


class EvidenceItem(BaseModel):
    """
    A single visual evidence artifact produced by analysis.
    """

    type: str = Field(
        ...,
        description=(
            "Evidence type, e.g. image_a, heatmap, overlay, "
            "annotated_bboxes, attention_overlay."
        ),
    )

    label: str = Field(
        default="",
        description="Human-readable evidence label.",
    )

    url: Optional[str] = Field(
        default=None,
        description="URL from which the frontend can retrieve the evidence.",
    )

    path: Optional[str] = Field(
        default=None,
        description="Backend filesystem path of the evidence artifact.",
    )

    description: str = Field(
        default="",
        description="Description of what the evidence represents.",
    )


class Metric(BaseModel):
    """
    Metric displayed by the frontend.
    """

    value: Any = None
    unit: str = ""


class AnalysisResult(BaseModel):
    """
    Standard response returned by the SatQuery backend.

    The response is intentionally aligned with the existing Streamlit
    frontend so the frontend can consume live backend results without
    redesigning the result UI.
    """

    success: bool = Field(
        ...,
        description="Whether analysis completed successfully.",
    )

    status: str = Field(
        default="success",
        description="success, error, or partial.",
    )

    analysis_id: str = Field(
        default="",
        description="Unique identifier for this analysis.",
    )

    query: str = Field(
        default="",
        description="Original user query.",
    )

    mode: str = Field(
        default="auto_detect",
        description="Analysis mode used for the request.",
    )

    task: str = Field(
        default="vqa",
        description="Internal task identifier.",
    )

    detected_task: Optional[DetectedTask] = Field(
        default=None,
        description="Task selected by the routing/query-understanding stage.",
    )

    answer: str = Field(
        default="",
        description="Natural-language answer generated by the analysis.",
    )

    confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Overall analysis confidence from 0 to 1.",
    )

    confidence_breakdown: dict[str, Any] = Field(
        default_factory=dict,
        description="Breakdown of confidence across analysis components.",
    )

    summary_bullets: list[str] = Field(
        default_factory=list,
        description="Short summary points for the result UI.",
    )

    metrics: dict[str, Metric] = Field(
        default_factory=dict,
        description="Analysis metrics displayed by the frontend.",
    )

    evidence: list[EvidenceItem] = Field(
        default_factory=list,
        description="Visual evidence artifacts.",
    )

    visual_evidence: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Frontend-compatible visual evidence payload. "
            "The API client may convert evidence URLs into images."
        ),
    )

    output_paths: list[str] = Field(
        default_factory=list,
        description="Backend paths of generated output files.",
    )

    statistics: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional analysis statistics.",
    )

    trace: list[TraceItem] = Field(default_factory=list)
    analysis_trace: list[TraceItem] = Field(default_factory=list)

    error: Optional[str] = Field(
        default=None,
        description="Error message when analysis fails.",
    )